sudo: false
language: go
go:
- 1.13.x

before_install:
- cd ../../../
- mv ./github.com/VirtusLab/jira-stats ./
- cd ./jira-stats/jira-stats-serverless

install:
- make init

script:
- make build
- make tests

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - vendor
